# Generated by Django 2.2.4 on 2020-09-17 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('favbookapp', '0003_auto_20200916_2332'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='uploaded_by_id',
            new_name='uploaded_by',
        ),
    ]
